### ISSUE TITLE
Support for pickerInput?

### ISSUE THREAD

**Issue by m-merchant** [merlinoa/shinyFeedback#10]
Just wondering if shinyFeedback was compatible with pickerInput since it works for selectizeInput? 

In the app below, I would like to display a danger message to the user if the value of the pickerInput (input$state2) is equal to the value of the selectizeInput (input$state1). It works nicely when both are selectizeInputs but seems to fail if one is a pickerInput. It doesn't throw an error so I wasn't sure if this was due to the feedbackDanger condition being incorect or something else.   

```
library(shiny)
library(shinyFeedback)
library(shinyWidgets)


ui <- fluidPage(shinyFeedback::useShinyFeedback(),
                selectizeInput('state1', 'Select state 1', choices = state.name, 
                               selected = character(0), 
                               options = list(placeholder = "Search by name")),
                
                
                # selectizeInput('state2', 'Select state 2', choices = state.name, 
                #                selected = character(0), 
                #                options = list(placeholder = "Search by name")),
                
                
                pickerInput("state2", "Select state 2:", choices = state.name,
                            multiple = T),
                
                actionButton("click", "Click"),
                
                verbatimTextOutput("statez")
)

server <- function(input, output, session) {
  
  
  states <- eventReactive(input$click, {
    
    # feedbackDanger("state1", is.null(input$state1), "Please select a state.")
    # 
    # feedbackDanger("state2", is.null(input$state2), "Please select a state.")
    
    condition <- ((!is.null(input$state1) & !is.null(input$state2)) && (input$state1 == input$state2))
    
    feedbackDanger("state2", condition, "State 1 and state 2 cannot be the same.")
    
    req(!is.null(input$state1), !is.null(input$state2), input$state1 != input$state2)
    
    return(paste(input$state1, input$state2, collapse = " "))
    
  })
  
  output$statez <- renderText({
    
    states()
    
  })
  
 
}

shinyApp(ui, server)
  


```

**Comment by merlinoa** [comment]
@Merchant93 Thank you for the issue and reprex!  No unfortunately `pickerInput` is not supported at this time.  Hopefully I can find the time to add it in the future. 

There should be an error thrown to the javascript console in your browser when you try and use an unsupported input.

**Comment by merlinoa** [comment]
@m-merchant At long last `shinyWidgets::pickerInput()` is now supported in the development version of shinyFeedback here on GitHub.  You can install using `remotes::install_github("merlinoa/shinyFeedback")`.  Your above code with `pickerInput()` should work now.  Please try it out and let me know if you run into any bugs!
