### ISSUE TITLE
Conditions that result in empty logical trigger feedback

### ISSUE THREAD

**Issue by hallieswan** [merlinoa/shinyFeedback#11]
Thanks for the cool package! I recently answered a [question](https://stackoverflow.com/questions/54563960/r-shiny-how-to-display-feedback-message-if-two-inputs-have-the-same-value-usi) on stackoverflow about your package. I think the asker's issue may be due to a small bug.

### Issue

When a condition returns an empty logical, an empty object is passed to the `checkFeedback` function. Empty objects are [truthy](https://developer.mozilla.org/en-US/docs/Glossary/Truthy), and so are "considered `true` when encountered in a Boolean context." So when `checkFeedback` evaluates the value: 

```
if (message.condition) {
    
   ....
```

the statement returns `true` and the `feedback` message is displayed.

### Example

In this example, the feedback is supposed to display if `input$state1 == input$state2`. However, if `input$state1` or `input$state2` is `NULL`, the feedback is displayed.

```
library(shiny)
library(shinyFeedback)


ui <- fluidPage(shinyFeedback::useShinyFeedback(),
                selectizeInput('state1', 'Select state 1', choices = state.name, 
                               multiple = T, 
                               options = list(placeholder = "Search by name", maxItems = 1)),

                selectizeInput('state2', 'Select state 2', choices = state.name, 
                               multiple = T, 
                               options = list(placeholder = "Search by name", maxItems = 1)),

                actionButton("click", "Click"),

                textOutput("states")
)

server <- function(input, output, session) {

  values = reactiveValues(states = NULL)

  observeEvent(input$click, {

    feedbackDanger("state1", input$state1 == input$state2, "")

    feedbackDanger("state2", input$state2 == input$state1, "State 1 and state 2 cannot be the same.")

    req(!is.null(input$state1), !is.null(input$state2), input$state1 != input$state2)

    values$states <- paste(input$state1, input$state2)

  })

  output$states <- renderText({

    values$states

  })
}

shinyApp(ui, server)
```

### Possible Solution

The if statement in `checkFeedback` could be changed to use `===`, so only booleans with value `true` will trigger the feedback. This worked locally for me: 

```
if (message.condition === true) {

   ....
```

Thanks again for the cool package!

**Comment by merlinoa** [comment]
@hallieswan I'm glad you like the package! and thanks very much for this excellent issue and reproducible example!  Very nicely done.  

Yes this is certainly a bug.  I believe your proposed solution fixed it.
