### ISSUE TITLE
Document feedback variations in one file

### ISSUE THREAD

**Issue by hadley** [merlinoa/shinyFeedback#18]
I think it would make sense to document feedback and all its variations in a single file, so that they're easier to compare and contrast. I'd be happy to do a PR if you were interested.

**Comment by merlinoa** [comment]
Thanks!  The feedback variation have been documented in a single file with caa6d71a2344f0b1ec5c55cbd50261d265533296 . Note the old `feedback()` function and its variation are now defunct in favor of the new `showFeedback()` and `hideFeedback()` functions.  See #19 for additional information.
