### ISSUE TITLE
Multiple feedbacks (with priority) for single input

### ISSUE THREAD

**Issue by merlinoa** [merlinoa/shinyFeedback#2]
shinyFeedback currently only properly supports 1 `feedback()` function per input.

Enhancement: Add support for multiple feedback messages per input.  

The current plan is to add a `priority` argument to the `feedback()` function which will be used to control the order that the feedback conditions are checked and make sure to only display the desired feedback message.

**Comment by merlinoa** [comment]
support for multiple feedback messages for a single input added in commit 7dbc5e32279218868baefa961ee69aa6e9861c8a

All feedback messages for a single input should be written in the same observer and the feedback message with the higher priority should appear in the code below lower priority feedbacks.  Additional documentation to come.

**Comment by sowla** [comment]
Hi! Thank you for your awesome package! I'm not sure if I understood correctly that multiple feedback messages should work even if the first but not the second condition is met? If so, that doesn't seem to be the case for me.. as a user, it's not a problem because I can easily add if statements :) I just wanted to let you know in case it's behaving unexpectedly. Thanks again!

----------

with this code only the second `feedbackWarning()` works in my hand:
```
library(shiny)
library(shinyFeedback)

ui <- fluidPage(
  useShinyFeedback(), # include shinyFeedback
  
  selectizeInput(
    "blah",
    "test multiple warnings",
    choices = c("1", "2", "3")
  )
)

server <- function(input, output) {
  observeEvent(input$blah, {
    feedbackWarning(
      inputId = "blah",
      condition = input$blah != 2,
      text = "first one"
    )
    feedbackWarning(
      inputId = "blah",
      condition = input$blah == 2,
      text = "second one"
    )
  })
}

shinyApp(ui, server)
```

this works though :)
```
  observeEvent(input$blah, {
    if (input$blah != 2) {
      feedbackWarning(
        inputId = "blah",
        condition = input$blah != 2,
        text = "first one"
      )
    }
    if (input$blah == 2) {
      feedbackWarning(
        inputId = "blah",
        condition = input$blah == 2,
        text = "second one"
      )
    }
  })
```

my session info:
shiny                 * 1.1.0   2018-05-17 CRAN (R 3.5.0)
shinyFeedback * 0.1.0   2018-08-20 CRAN (R 3.5.0)

**Comment by merlinoa** [comment]
Thanks @sowla !

The second condition will always override the first.  So if the first condition is `TRUE`, but the second condition is `FALSE` then no feedback will be shown.  So in your first app above, it is expected that only the second feedback message will show as the "condition" argument to the second `feedbackWarning()` is always `FALSE` when the first is `TRUE`.  

I would suggest that you just use `if` statements rather than relying on the position of the call to `feedback*()` as it probably makes for easier to reason about the code.

**Comment by sowla** [comment]
Oh, sorry, I misunderstood the functionality!

Thank you for the quick response! :)

**Comment by snhansen** [comment]
The above code using `if` statements doesn't work for me. Whichever warning is triggered first is stuck and I can't get it to disappear even if I choose an input that shouldn't trigger a warning. Here's a minimal example:

```
library(shiny)
library(shinyFeedback)

ui <- fluidPage(
  sidebarLayout(
    sidebarPanel(
      numericInput("n",
                   label="Number of observations:",
                   value=100)
    ),
    mainPanel(
      shinyFeedback::useShinyFeedback()
    )
  )
)

server <- function(input, output) {
  observe({se
    case1 <- input$n>100
    case2 <- input$n<0
    if (case1) {
      shinyFeedback::feedbackWarning("n", case1, paste0("Something"))
    }
    if (case2) {
      shinyFeedback::feedbackWarning("n", case2, paste0("Something else"))
    }
  })
}

shinyApp(ui = ui, server = server)
```
