### ISSUE TITLE
move Shiny functions from `tychobratools` to `shinyFeedback`

### ISSUE THREAD

**Issue by merlinoa** [merlinoa/shinyFeedback#24]
Let's go ahead and move these functions:

- `show_toast`: let's vendor the actual toastr js with shinyFeedback rather than using it from the shinytoastr package.  We will need a new `shinyFeedback::useToastr()` function to load up the toastr js on the client side.
- `loading_button`
- `value_box_module`

shinyFeedback uses the lower camel case rather than snake case.  To be consistent, please switch the above functions to use lowerCamelCase.

**Comment by phoward38** [comment]
`loadingButton`:
- Created branch `loadingButton`
- **NOTE:** @merlinoa is handling `loadingButton` & making a PR
- [x] Review `loadingButton` PR
- [x] Source in only necessary font-awesome JS/CSS

`showToast`:
- Created branch `add/showToast`
- [x] Refer to/compare commits from `loadingButton` branch (PR: #26) & apply same changes
- [x] Test `showToast` w/ new `useShinyFeedback` function w/ arguments
- [x] Confirm correct documentation

`valueBoxModule`:
- [x] Create `add/valueBoxModule` branch

Other:
- [x] Check for correct resource paths
- [x] Confirm correct dependencies

**IMPORTANT:**
- [x] Update `loadingButton` & `resetLoadingButton` functions in Polished
- [x] Update reset events in Polished JS scripts for new `loadingButton`
- [x] Update/create vignette(s)
