### ISSUE TITLE
example app crashing

### ISSUE THREAD

**Issue by ismirsehregal** [merlinoa/shinyFeedback#25]
Just FYI, the [example app](https://tychobra.shinyapps.io/shinyFeedbackExamples/) hosted on shinyapps.io crashes once the numericInput is empty:

![screen](https://user-images.githubusercontent.com/36849480/79846477-c926a780-83be-11ea-87eb-a31b0f186120.gif)

**Comment by merlinoa** [comment]
Thanks @ismirsehregal!  This has been fixed with 36140eaea993de70963e2b886b198517f7f5d26a

**Comment by ismirsehregal** [comment]
It's still crashing for the dateInput.

**Comment by merlinoa** [comment]
Fixed thanks again!
