### ISSUE TITLE
optionally halt reactivity

### ISSUE THREAD

**Issue by merlinoa** [merlinoa/shinyFeedback#3]
Add an argument to feedback() that can halt the input from triggering the reactive chain if the feedback() function's condition argument is TRUE

**Comment by rpodcast** [comment]
I just discovered this great package and I'm eager to try it in my apps.  If it was possible to have this functionality of stopping the reactive chain the particular input depends on, it would save a ton of backend effort to put those stops in myself.

**Comment by merlinoa** [comment]
Hi Eric.  I am a big fan of the R podcast!  Thanks for you work on the podcast and for your comment here.

I originally thought this functionality would be helpful, but after starting to implement it I did not feel like it worked well with the Shiny reactivity model.  I couldn't come up with a way to add this feature that was more straight forward than the normal Shiny model.  This is how I would normally set up an app to display the feedback and not update the output:

```
library(shiny)
library(shinyFeedback)

ui <- fluidPage(
  useShinyFeedback(), # include shinyFeedback
  
  numericInput(
    "my_num",
    "Warn if Negative",
    value = 0
  ),
  
  verbatimTextOutput("my_output")
)

server <- function(input, output) {
  show_feedback <- reactive({
    input$my_num < 0
  })  
  
  observeEvent(show_feedback(), {
    feedbackWarning(
      inputId = "my_num",
      condition = show_feedback()
    )
  })
  
  output$my_output <- renderPrint({
    req(!show_feedback())
    input$my_num
  })
}

shinyApp(ui, server)
```

Let me know if you have an idea for a better implementation.  PRs are welcome!
