### ISSUE TITLE
Error 404 on toastr.js.map

### ISSUE THREAD

**Issue by msaltieri** [merlinoa/shinyFeedback#32]
When using the package I receive in the browser JS console the following message:

```
Failed to load resource: the server responded with a status of 404 (Not Found)
http://127.0.0.1:7365/toastr-2.1.4/js/toastr.js.map
```

It seems that the package `*.js.map` file is not loaded correctly. Is it something you have already noticed?

**Comment by merlinoa** [comment]
Your browser only attempts to download the "*.js.map" files when you have developer tools open, so I don't believe this is an actual issue for end users.  Nevertheless, it is certainly better practice to include the js.map files, so I added it: 87540ca508e4e14b9dd4aafa2a6b27371ceea3f8

Thanks @msaltieri for opening the issue and bringing this to my attention!
