### ISSUE TITLE
Feature request: affect multiple widgets in a single call

### ISSUE THREAD

**Issue by PuzzledFace** [merlinoa/shinyFeedback#34]
I would find it helpful if a single `shinyFeedbackXXX` call could affect more than one widget.  For example, perhaps something along the lines of:

```
feedbackDanger(
  inputId=c("sex", "pregnant"),
  show=input$sex == "M" & input$pregnant == "Y",
  text="Males cannot be pregnant! [Unless they're seahorses...]"
)
```

**Comment by merlinoa** [comment]
Yea this could definitely be useful.  I'll plan to incorporate it into shinyFeedback with the next round of feature updates.

**Comment by merlinoa** [comment]
After further consideration I have decided not to implement this feature.  I do think it could be useful, but I'm not convinced it is worth the slight increase in complexity.  I would like to keep shinyFeedback as simple as possible.  Thanks again for the suggestion.
