### ISSUE TITLE
Feature request: test for multiple conditions in a single call

### ISSUE THREAD

**Issue by PuzzledFace** [merlinoa/shinyFeedback#35]
Because only the last `feedbackXXXX` call whose `show` condition evaluates to true can lead to cumbersome code when there are multiple potential issues that require feedback.  A more elegant solution might be to allow `show` to support named lists.  The name would provide the message to display if the corresponding condition is met.  For example (untested code):

```
feedbackDanger(
  inputId="admission",
  show=list(
         "Disease onset must precede hospital admission"=quote(input$admission < input$onset),
         "Date of hospital admission must be provided"=quote(!isTruthy(input$admission))
       )
)
```

**Comment by merlinoa** [comment]
Thanks for the suggestion, but IMO it is much more simple to just use an if/else statement before the call to `feedbackDanger()`.  Let me know if you disagree and we can discuss.

**Comment by PuzzledFace** [comment]
If the need is to select which *one* of several potential messages to display, then I see your point.  

I was really thinking of a situation in which *several* messages might need to be displayed at the same time.  In that case, the mechanics of constructing the message string will probably affect the clarity of the main logic of the app.  Putting all the conditions within a single call to `feedbackXXXX()`, to my mind at least, provides greater separation between error checking and program flow.  It also hands the nitty gritty of constructing the compound error message to `shinyFeedback`, which I like because I'm lazy.

My example above didn't make that clear.  Apologies.

Whether the issue is selecting one message from many or constructing a compound message, I think the suggestion provides greater clarity because of the greater separation between program logic and validation.  But I accept it's a matter or style and `shinyFeedback` is your package, so you get to make the call.

**Comment by merlinoa** [comment]
@PuzzledFace thanks very much for the suggestion.  I can see the argument for constructing error messages with shinyFeedback.  However, I am leaning towards not implementing this feature mainly for the sake of keeping shinyFeedback as simple as I can think to make it.  I may revisit at some point in the future, but for now I am going to go ahead and close this out.  Please feel free to reopen if you have more ideas on this issue.
