### ISSUE TITLE
create hex sticker

### ISSUE THREAD

**Issue by merlinoa** [merlinoa/shinyFeedback#39]
It would be awesome if we had a nice hex sticker. 

Not sure if this is the best way to make hex stickers, but here is a popular package package for making them: https://github.com/GuangchuangYu/hexSticker

Let's settle on a design before next release.  

@jimbrig any ideas?

**Comment by jimbrig** [comment]
I can help out with this.

[This PowerPoint template](https://github.com/merlinoa/shinyFeedback/files/4928810/hexsticker.pptx) is pretty helpful for quickly prototyping up hex stickers with the right dimensions.


I gave it a quick 10 minute try and made these 2 options:
(![shinyFeedback-checklist](https://user-images.githubusercontent.com/32652297/87616054-2f7f4580-c6e2-11ea-92a8-f8933c412412.png)
![shinyFeedback-satelite](https://user-images.githubusercontent.com/32652297/87616056-3017dc00-c6e2-11ea-9c0c-97f1ab583756.png)

**Comment by jimbrig** [comment]
What format would it need to be? SVG? ICO?

PP has some wild "artistic effects" too:
![image](https://user-images.githubusercontent.com/32652297/87616843-0c559580-c6e4-11ea-84e5-f43869f19d52.png)

**Comment by merlinoa** [comment]
Sweet!  png format is good.  I just added it to the README.  Do you think you could move the "shinyFeedback" title down a little and make it bigger?  If you can make that change, I think it is perfect.  Thanks!

**Comment by jimbrig** [comment]
yeah I can do that

**Comment by merlinoa** [comment]
completed with #40 thanks @jimbrig !
