### ISSUE TITLE
add `removeToast()` and `clearToast()` functions

### ISSUE THREAD

**Issue by merlinoa** [merlinoa/shinyFeedback#43]
These functions should call the `toastr.remove()` and `toastr.clear()` methods in the toastr JavaScript library.  They are useful for removing toasts messages after something happens. e.g. if you set the "timeOut' and "extendedTimeOut" options to 0, the toast will not be removed until either the user clicks the toast or it is removed with one of these methods.

**Comment by phoward38** [comment]
- [x] Add `keep_visible` argument to `showToast`, set to `FALSE` as default
  - When `keep_visible=TRUE`, overwrites `timeOut` & `extendedTimeOut` values in list for `.options` arg  & sets to 0

**Comment by phoward38** [comment]
Completed & created PR https://github.com/merlinoa/shinyFeedback/pull/44
