### ISSUE TITLE
Compatibility with previous shinyWidgets releases

### ISSUE THREAD

**Issue by ericnewkirk** [merlinoa/shinyFeedback#49]
I'm not sure this justifies creating an issue, but I wanted to put it somewhere in case anyone else runs into the same behavior. With shinyFeedback v0.3.0 and shinyWidgets v0.5.1 I can't get feedback to display for shinyWidgets::airDatepickerInput, but everything works fine for other widgets. Updating shinyWidgets to 0.5.3 resolves the problem.

**Comment by merlinoa** [comment]
Hi @ericnewkirk 

Thanks for opening this issue.  Hopefully it will help anyone else that runs into this problem.

Yes `shinyWidgets` changed the internal name that the `shinyWidgets::airDatpickerInput()` uses, so shinyFeedback was updated to support the new name.  The relevant commit to shinyFeedback is here if you are interested:  https://github.com/merlinoa/shinyFeedback/commit/4d4a620465a94659e4ae38445ae2d9d524cdb118

I think this is a reasonable update, so I am going to close this issue out.  Feel free to open if you have ideas for improvement.

**Comment by ericnewkirk** [comment]
Thanks @merlinoa - I agree it can be closed.
