### ISSUE TITLE
Updating feedback message

### ISSUE THREAD

**Issue by jl5000** [merlinoa/shinyFeedback#55]
Hi, I'm using feedbackDanger to show a message when an input is invalid. When I change the input to another invalid value, the feedback message doesn't change even though I'm providing a different text argument. Am I using this wrong? In the below example, changing the value to 4 gives a message, but changing it to 45 doesn't update the message:

``` r
library(shiny)
library(shinyFeedback)

ui <- fluidPage(
    shinyFeedback::useShinyFeedback(),
    shiny::numericInput("number", "Input value", value = NULL, 
                        min = 0, max = 3, step = 1)

)

server <- function(input, output) {

    shiny::observeEvent(input$number, ignoreNULL = FALSE, ignoreInit = TRUE, {

        if(is.null(input$number)) {
            err <- NULL
        } else if (input$number %in% 0:3) {
            err <- NULL
        } else {
            err <- paste0(input$number, " not valid")
        }

        shinyFeedback::feedbackDanger("number", !is.null(err), err)
    })
    
}

shinyApp(ui = ui, server = server)
```

<div style="width: 100% ; height: 400px ; text-align: center; box-sizing: border-box; -moz-box-sizing: border-box; -webkit-box-sizing: border-box;" class="muted well">Shiny applications not supported in static R Markdown documents</div>

<sup>Created on 2021-07-25 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by phoward38** [comment]
@jl5000 This issue has been resolved in the most recent development version, which can be installed with `remotes::install_github('merlinoa/shinyFeedback')`
