### ISSUE TITLE
add multiple condition

### ISSUE THREAD

**Issue by sravel** [merlinoa/shinyFeedback#6]
Hello!
Thanks for the  package, it is very easy to use and perfectly fulfills its function.
I have a question, I want to put 2 conditions maus I do not find how to do.
my conditions are: my input must be an integer positive.
I wrote:
observeEvent (input lesion_min_size $ ({
     feedbackWarning (
       inputId = "lesion_min_size",
       condition = c (input $ lesion_min_size <0, typeof (as.integer (input $ lesion_min_size)) == TRUE),
       text = "please add integer positive",
     )
   })
)

Thanks

Sebastien

**Comment by merlinoa** [comment]
The condition argument is intended to evaluate to either `TRUE` or `FALSE`.  perhaps you could try something like this instead:

```
observeEvent(input$lesion_min_size, {
    feedbackWarning(
      inputId = "lesion_min_size",
      condition = all(c(
        input$lesion_min_size <= 0,
        input$lesion_min_size  %% 1 == 0
      )),
      text = "please add integer positive"
    )
  })
```
